### ISSUE TITLE
Crashes If not provided a "logfile" parameter

### ISSUE THREAD

**Issue by proclamo** [acanimal/clyde#14]
In clyde.createMiddleware(options)'s options object there isn't default parameter for "logfile" property. If it is not set, it crashes.

**Comment by acanimal** [comment]
As a standalone app some options are optional (as I say in documentation) but as middleware the JS object you pass must contain all options, there are no default values.

I think I must put default values to middleware options too.

**Comment by acanimal** [comment]
Solved
